//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.29 at 09:25:25 PM EDT 
//


package gov.sbs.plugins.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="violation" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="beginline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="endline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="begincolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="endcolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="rule" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ruleset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="package" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="externalInfoUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "file"
})
@XmlRootElement(name = "pmd")
public class Pmd {

    @XmlElement(required = true)
    protected List<Pmd.File> file;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the file property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pmd.File }
     * 
     * 
     */
    public List<Pmd.File> getFile() {
        if (file == null) {
            file = new ArrayList<Pmd.File>();
        }
        return this.file;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="violation" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="beginline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="endline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="begincolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="endcolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="rule" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ruleset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="package" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="externalInfoUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "violation"
    })
    public static class File {

        @XmlElement(required = true)
        protected List<Pmd.File.Violation> violation;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the violation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the violation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getViolation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Pmd.File.Violation }
         * 
         * 
         */
        public List<Pmd.File.Violation> getViolation() {
            if (violation == null) {
                violation = new ArrayList<Pmd.File.Violation>();
            }
            return this.violation;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="beginline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="endline" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="begincolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="endcolumn" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="rule" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ruleset" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="package" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="externalInfoUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Violation {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "beginline", required = true)
            protected int beginline;
            @XmlAttribute(name = "endline", required = true)
            protected int endline;
            @XmlAttribute(name = "begincolumn", required = true)
            protected int begincolumn;
            @XmlAttribute(name = "endcolumn", required = true)
            protected int endcolumn;
            @XmlAttribute(name = "rule", required = true)
            protected String rule;
            @XmlAttribute(name = "ruleset", required = true)
            protected String ruleset;
            @XmlAttribute(name = "package", required = true)
            protected String _package;
            @XmlAttribute(name = "class", required = true)
            protected String clazz;
            @XmlAttribute(name = "externalInfoUrl", required = true)
            protected String externalInfoUrl;
            @XmlAttribute(name = "priority", required = true)
            protected String priority;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the beginline property.
             * 
             */
            public int getBeginline() {
                return beginline;
            }

            /**
             * Sets the value of the beginline property.
             * 
             */
            public void setBeginline(int value) {
                this.beginline = value;
            }

            /**
             * Gets the value of the endline property.
             * 
             */
            public int getEndline() {
                return endline;
            }

            /**
             * Sets the value of the endline property.
             * 
             */
            public void setEndline(int value) {
                this.endline = value;
            }

            /**
             * Gets the value of the begincolumn property.
             * 
             */
            public int getBegincolumn() {
                return begincolumn;
            }

            /**
             * Sets the value of the begincolumn property.
             * 
             */
            public void setBegincolumn(int value) {
                this.begincolumn = value;
            }

            /**
             * Gets the value of the endcolumn property.
             * 
             */
            public int getEndcolumn() {
                return endcolumn;
            }

            /**
             * Sets the value of the endcolumn property.
             * 
             */
            public void setEndcolumn(int value) {
                this.endcolumn = value;
            }

            /**
             * Gets the value of the rule property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRule() {
                return rule;
            }

            /**
             * Sets the value of the rule property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRule(String value) {
                this.rule = value;
            }

            /**
             * Gets the value of the ruleset property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleset() {
                return ruleset;
            }

            /**
             * Sets the value of the ruleset property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleset(String value) {
                this.ruleset = value;
            }

            /**
             * Gets the value of the package property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPackage() {
                return _package;
            }

            /**
             * Sets the value of the package property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPackage(String value) {
                this._package = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the externalInfoUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternalInfoUrl() {
                return externalInfoUrl;
            }

            /**
             * Sets the value of the externalInfoUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternalInfoUrl(String value) {
                this.externalInfoUrl = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriority(String value) {
                this.priority = value;
            }
            
	        	@javax.xml.bind.annotation.XmlTransient
	            private String guiltyParty;
	            
	            public String getGuiltyParty() {
	            	return guiltyParty;
	            }
	            
	            public void setGuiltyParty(String gp) {
	            	this.guiltyParty = gp;
	            }
	            
	            @javax.xml.bind.annotation.XmlTransient
				private String code;
	            
	            public String getCode() {
	            	return code;
	            }
	            
	            public void setCode(String code) {
	            	this.code = code;
	            }
	            
	            @Override
	            public String toString() {
	            	StringBuilder sb = new StringBuilder();
	            	sb.append("guiltyParty : " + guiltyParty);
	            	sb.append("\nbeginline : " + beginline);
	            	sb.append("\nendline : " + endline);
	            	sb.append("\nbegincolumn : " + begincolumn);
	            	sb.append("\nendcolumn : " + endcolumn);
	            	sb.append("\nrule : " + rule);
	            	sb.append("\nruleset : " + ruleset);
	            	sb.append("\npackage : " + _package);
	            	sb.append("\nclazz : " + clazz);
	            	sb.append("\nexternalInfoUrl : " + externalInfoUrl);
	            	sb.append("\npriority : " + priority);
	            	sb.append("\nvalue : " + value);
	            	sb.append("\ncode : " + code);
	            	return sb.toString();
	            }
	        
        }

    }

}
