//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.01 at 09:28:16 PM EDT 
//


package gov.sbs.plugins.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subreport" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="guiltyParty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fullClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="startLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="endLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="startColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="endColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="violation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="violationRuleSet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{}reportType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subreport"
})
@XmlRootElement(name = "report")
public class Report {

    @XmlElement(required = true)
    protected List<Report.Subreport> subreport;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the subreport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subreport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubreport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Report.Subreport }
     * 
     * 
     */
    public List<Report.Subreport> getSubreport() {
        if (subreport == null) {
            subreport = new ArrayList<Report.Subreport>();
        }
        return this.subreport;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="guiltyParty" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fullClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="startLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="endLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="startColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="endColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="violation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="violationRuleSet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{}reportType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class Subreport {

        @XmlElement(required = true)
        protected List<Report.Subreport.Entry> entry;
        @XmlAttribute(name = "name", required = true)
        protected ReportType name;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Report.Subreport.Entry }
         * 
         * 
         */
        public List<Report.Subreport.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<Report.Subreport.Entry>();
            }
            return this.entry;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link ReportType }
         *     
         */
        public ReportType getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReportType }
         *     
         */
        public void setName(ReportType value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="guiltyParty" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fullClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="startLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="endLine" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="startColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="endColumn" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="violation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="violationRuleSet" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "guiltyParty",
            "fullClass",
            "startLine",
            "endLine",
            "startColumn",
            "endColumn",
            "code",
            "violation",
            "violationRuleSet",
            "message"
        })
        public static class Entry {

            @XmlElement(required = true)
            protected String guiltyParty;
            @XmlElement(required = true)
            protected String fullClass;
            protected int startLine;
            protected int endLine;
            protected int startColumn;
            protected int endColumn;
            @XmlElement(required = true)
            protected String code;
            @XmlElement(required = true)
            protected String violation;
            @XmlElement(required = true)
            protected String violationRuleSet;
            @XmlElement(required = true)
            protected String message;

            /**
             * Gets the value of the guiltyParty property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuiltyParty() {
                return guiltyParty;
            }

            /**
             * Sets the value of the guiltyParty property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuiltyParty(String value) {
                this.guiltyParty = value;
            }

            /**
             * Gets the value of the fullClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullClass() {
                return fullClass;
            }

            /**
             * Sets the value of the fullClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullClass(String value) {
                this.fullClass = value;
            }

            /**
             * Gets the value of the startLine property.
             * 
             */
            public int getStartLine() {
                return startLine;
            }

            /**
             * Sets the value of the startLine property.
             * 
             */
            public void setStartLine(int value) {
                this.startLine = value;
            }

            /**
             * Gets the value of the endLine property.
             * 
             */
            public int getEndLine() {
                return endLine;
            }

            /**
             * Sets the value of the endLine property.
             * 
             */
            public void setEndLine(int value) {
                this.endLine = value;
            }

            /**
             * Gets the value of the startColumn property.
             * 
             */
            public int getStartColumn() {
                return startColumn;
            }

            /**
             * Sets the value of the startColumn property.
             * 
             */
            public void setStartColumn(int value) {
                this.startColumn = value;
            }

            /**
             * Gets the value of the endColumn property.
             * 
             */
            public int getEndColumn() {
                return endColumn;
            }

            /**
             * Sets the value of the endColumn property.
             * 
             */
            public void setEndColumn(int value) {
                this.endColumn = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the violation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getViolation() {
                return violation;
            }

            /**
             * Sets the value of the violation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setViolation(String value) {
                this.violation = value;
            }

            /**
             * Gets the value of the violationRuleSet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getViolationRuleSet() {
                return violationRuleSet;
            }

            /**
             * Sets the value of the violationRuleSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setViolationRuleSet(String value) {
                this.violationRuleSet = value;
            }

            /**
             * Gets the value of the message property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMessage() {
                return message;
            }

            /**
             * Sets the value of the message property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMessage(String value) {
                this.message = value;
            }

        }
        
				public String getMostGuilty() {
		        	java.util.Map<String, Integer> runningTotal = new java.util.HashMap<String, Integer>();
		        	for (gov.sbs.plugins.domain.Report.Subreport.Entry e : getEntry()) {
		        		if (runningTotal.containsKey(e.getGuiltyParty())) {
		        			runningTotal.put(e.getGuiltyParty(),runningTotal.get(e.getGuiltyParty()) + 1);
		        		} else {
		        			runningTotal.put(e.getGuiltyParty(), new Integer(1));
		        		}
		        	}
		        	
		        	String mostGuilty = "";
		        	Integer violationCount = new Integer(0);
		        	for (String key : runningTotal.keySet()) {
		        		if (runningTotal.get(key) > violationCount) {
		        			mostGuilty = key;
		        			violationCount = runningTotal.get(key);
		        		}
		        	}
		        	
		        	if (violationCount == 0) {
		        		return "There are no violations";
		        	} else if (violationCount == 1) {
		        		return mostGuilty + " (" + violationCount + " Violation)";
		        	} else {
		        		return mostGuilty + " (" + violationCount + " Violations)";
		        	}
		        }
	        
    }
    
			    @Override
			    public String toString() {
			    	StringBuffer sb = new StringBuffer();
			    	sb.append("Vanderblame Report (" + timestamp + ")");
			    	
			    	for (Subreport r : subreport) {
			    		sb.append("\n - Report Type : " + r.getName());
			    		
			    		sb.append("\n   - Entrie(s) ::: ");
			    		for (gov.sbs.plugins.domain.Report.Subreport.Entry e : r.getEntry()) {
			    			sb.append("\n     - " + e.getGuiltyParty() + " : " + e.getFullClass());
			    		}
			    		sb.append("\n\n\n");
			    	}
			    	return sb.toString();
			    }
	        
}
